---
- name: Deploy to testing Docker container
  hosts: test
  vars:
    project_port: 3000
    server_names: 'localhost,www.localhost'
    ssl_sign_by: 'self'
    use_ssl: true
    env:
      print_this: 'Testing deployment: X Ã† A-12'
  roles:
    - role: practical-ansible.nginx_docker
